# Polynomial Regression

In [2]:
# Polynomial Regression

# load dataset

import pandas as pd
import numpy as np
df = pd.read_csv('/content/Student_Performance.csv')
df.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [17]:
from os import X_OK
def polynomial_regression(X , y , degree):
  # 1. matrix formulation
  # transporse metrix
  # xTx matrix
  trans_x = np.transpose(X)
  # xTy
  trans_x_y = np.transpose(y)

  # inverse matrix of xTx
  xTx = np.linalg.inv(np.dot(trans_x , X))

  # calculate coefficients
  beta = np.dot(np.dot(xTx , trans_x) , trans_x_y)

  # predict
  y_pred = np.dot(X , beta)

  return xTx , beta , y_pred





In [18]:
# encode categorical data

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Extracurricular Activities'] = le.fit_transform(df['Extracurricular Activities'])
df.head()

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0              7               99                           1            9   
1              4               82                           0            4   
2              8               51                           1            7   
3              5               52                           1            5   
4              7               75                           0            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [19]:
# apply the model
degree = 2
X = df.drop(['Performance Index'] , axis = 1)
y = df['Performance Index']
polynomial_regression(X , y , degree)

(array([[ 1.34772459e-05, -4.15065311e-07, -4.21990594e-06,
         -4.39954469e-06, -1.24763913e-06],
        [-4.15065311e-07,  1.96909620e-07, -1.30050190e-06,
         -1.35891666e-06, -3.25883709e-07],
        [-4.21990594e-06, -1.30050190e-06,  3.89699887e-04,
         -9.10108304e-06, -3.65880185e-06],
        [-4.39954469e-06, -1.35891666e-06, -9.10108304e-06,
          2.16007111e-05, -3.14231222e-06],
        [-1.24763913e-06, -3.25883709e-07, -3.65880185e-06,
         -3.14231222e-06,  1.14634537e-05]]),
 array([ 2.1959844 ,  0.8172197 , -1.17087492, -1.50360149, -0.2656486 ]),
 array([81.30770374, 69.25024947, 47.01869714, ..., 66.47721129,
        87.33808473, 63.55168776]))

In [23]:
# sklearn polynomial regression'

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X)
lin_reg = LinearRegression()
lin_reg.fit(X_poly , y)
lin_reg.coef_
lin_reg.intercept_
y_pred = lin_reg.predict(X_poly)
y_pred


array([91.90431146, 63.20589056, 45.07267501, ..., 73.0163237 ,
       94.41347058, 65.26359525])